steps:
  - input: 'Information please'
    key: information-step
    prompt: 'Fill out the details for test run'
    fields:
      - text: 'Base URL'
        key: 'base-url'
        hint: 'On a real pipeline you probably want this set up elsewhere. Example: https://example.com'
      - text: 'API Auth Token'
        key: 'auth-token'
        hint: 'Add your Bare token here if your API requires it. Single use token is recommended.'
        required: false
      - text: 'Concurrent IPs'
        key: 'concurrent-ips'
        hint: 'Number of unique IPs that the virtual users will be spread across'
        default: '1'
      - text: 'Max Virtual Users'
        key: 'max-virtual-users'
        default: '10'
        hint: 'Max number of concurrent users across all unique IPs'
      - text: 'Virtual Users Ramp Up Duration'
        key: 'virtual-users-ramp-up-duration'
        default: '1m'
        hint: 'Time for going from zero to maximum virtual users'
      - text: 'Virtual Users Sustained Duration'
        key: 'virtual-users-sustained-duration'
        default: '3m30s'
        hint: 'Time for sustaining the maximum number of virtual users'
      - text: 'Virtual Users Ramp Down Duration'
        key: 'virtual-users-ramp-down-duration'
        default: '30s'
        hint: 'Time for going from maximum virtual users count to zero'
  - label: ':pipeline: Build pipeline'
    depends_on: information-step
    command: '.buildkite/lib/build-k6-pipeline.sh | buildkite-agent pipeline upload'
    agents:
      queue: '*'
